// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entrenadores.Models;

namespace entrenadores.Migrations
{
    [DbContext(typeof(EntrenadorContext))]
    [Migration("20210519001822_MigracionInicial")]
    partial class MigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("entrenadores.Models.Entrenador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("EntrenadorId")
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<int>("PuebloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntrenadorId");

                    b.HasIndex("PuebloId");

                    b.ToTable("Entrenadores");
                });

            modelBuilder.Entity("entrenadores.Models.Pueblo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pueblos");
                });

            modelBuilder.Entity("entrenadores.Models.Entrenador", b =>
                {
                    b.HasOne("entrenadores.Models.Entrenador", null)
                        .WithMany("Entrenadores")
                        .HasForeignKey("EntrenadorId");

                    b.HasOne("entrenadores.Models.Pueblo", "Pueblo")
                        .WithMany("Entrenadores")
                        .HasForeignKey("PuebloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pueblo");
                });

            modelBuilder.Entity("entrenadores.Models.Entrenador", b =>
                {
                    b.Navigation("Entrenadores");
                });

            modelBuilder.Entity("entrenadores.Models.Pueblo", b =>
                {
                    b.Navigation("Entrenadores");
                });
#pragma warning restore 612, 618
        }
    }
}
